src/routes/index.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from werkzeug.security import check_password_hash
from src.database.db import db


# Entidades
from src.models.models import Paciente, Especialista, Alimento, Comida, AC
# //

ind = Blueprint('index', __name__)

# Pagina principal <
@ind.route('/')
def index():
    return render_template('index.html')
# // >

# Tipo de usuario <
@ind.route('/registro')
def registro():
    return render_template('registro.html')
# // >

# Iniciar sesion <
@ind.route('/login', methods=['GET','POST'])
def login():
    if request.method == "POST":
        _correo = request.form['ind-correo']
        _clave = request.form['ind-clave']

        # Check if the user exists in the database
        account = db.session.query(Paciente.id_paciente, Paciente.clave).filter(Paciente.correo == _correo).first()
        
        # if account and check_password_hash(account.clave, _clave):
        #     session['logueado'] = True
        #     session['id'] = account.id_paciente
        #     _id = session['id']
            
        #     return redirect(url_for('paciente.inicio', id=_id))
        if account: # Temporal para hacer pruebas sin seguridad
            session['logueado'] = True
            session['id'] = account.id_paciente
            _id = session['id']
        
            return redirect(url_for('paciente.inicio', id=_id))


        else:    
            account = db.session.query(Especialista.id_espe, Especialista.clave).filter(Especialista.correo == _correo).first()

            # if account and check_password_hash(account.clave, _clave):
            #     session['logueado'] = True
            #     session['id'] = account.id_empleado
            #     _id = session['id']
            #     return redirect(url_for('especialista.inicio', id=_id))
            if account: # Temporal para hacer pruebas sin seguridad
                session['logueado'] = True
                session['id'] = account.id_espe
                _id = session['id']
            
                return redirect(url_for('especialista.inicio', id=_id))            
            else:
                return render_template('login.html', mensaje = 'El usuario no se encuentra registrado o la contraseña es incorrecta')

    else:
        return render_template('login.html')
# // >

# Cerrar sesion del usuario <
@ind.route('/logout/<id>', methods=['GET'])
def logout(id):
    
    user = Paciente.query.get(id)

    if user is None:
        return "Usuario no encontrado"

    if (user.id_paciente == int(id) or user.id_empleado == int(id)):
        session.pop('id', None)
        session.clear()
        return redirect(url_for('index.index'))
    else:
        return "Error 404, No se pudo cerrar la sesion"
# // >


# TODO: Falta recuperar contraseña

src/routes/paciente.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from werkzeug.security import generate_password_hash
from sqlalchemy.orm import aliased
from sqlalchemy import cast, Date
from src.database.db import db
from datetime import datetime

# Entidades
from src.models.models import Especialista, Paciente, Comida, AC, Alimento
# //

# FIXME: Hay que agregar los try-catch en todos los metodos

pac = Blueprint('paciente', __name__)

# Registrar <
@pac.route('/registro_paciente', methods=['GET','POST'])
def registro():
  if request.method == "POST":
    pri_nombre = request.form['pac-pri-nombre']
    pri_apellido = request.form['pac-pri-apellido']
    seg_apellido = request.form['pac-seg-apellido']
    sexo = request.form['pac-sexo']
    correo = request.form['pac-correo']
    telefono = request.form['pac-telefono']
    clave = request.form['pac-clave']
    fecha_nacimiento = (request.form['pac-fecha-nacimiento'])
    seg_nombre = request.form['pac-seg-nombre']

    # Hacer la contraseña segura
    hashed_clave = generate_password_hash(clave)   
    # //

    # Se inserta el paciente en la tabla
    new_pac = Paciente (
        pri_nombre,
        pri_apellido,
        seg_apellido,
        sexo,
        correo,
        telefono,
        hashed_clave,
        fecha_nacimiento,
        seg_nombre
    )

    db.session.add(new_pac)
    db.session.commit()
    db.session.close()

    flash("Paciente agregado correctamente", "success")
    # //

    return redirect(url_for('index.index'))
  
  else:
      return render_template('p_registro.html')
# // > 

# Inicio <
@pac.route('/inicio/<id>', methods=['GET', 'POST'])
def inicio(id):

    # Consulta de todos los datos del paciente
    get_pac = db.session.query(Paciente).filter(Paciente.id_paciente == id).first()

    if get_pac is None:
        flash('Paciente no encontrado.', 'danger')
        return redirect(url_for('index.index')) 
    # //

    # Consulta de las comidas del paciente
    tipo = (
        db.session.query(Comida.tipo, Comida.fecha_ini)
        .filter(Comida.id_paciente == id)
        .filter(Comida.comentario != None)
    ).all()
    # //

    # Fecha Actual
    date = datetime.now()
    formatted_date = date.strftime("%b. %d")
    # //
    
    if request.method == "POST":

        # Extraigo la fecha del buscador
        fecha_str = request.form['pac-fecha']
        fecha = datetime.strptime(fecha_str, '%Y-%m-%d')
        # //

        date = fecha.strftime('%B, %d %Y') # Formateo de la fecha de la consulta

        # Consulta de las comidas del paciente
        tipo = (
            db.session.query(Comida.tipo, Comida.fecha_ini)
            .filter(cast(Comida.fecha_ini, Date) == fecha.date())
            .filter(Comida.id_paciente == id)
        ).all()
        # //

        db.session.close()
        
        return render_template('p_inicio.html', get_pac=get_pac, formatted_date=formatted_date, date=date, tipo=tipo, fecha=fecha)

    return render_template("p_inicio.html", get_pac=get_pac, formatted_date=formatted_date)
# // >

# Perfil <
@pac.route('/perfil/<id>', methods=["GET"])
def perfil(id):
    paciente = Paciente.query.get(id)

    if paciente is None:
        flash("Paciente no encontrado", "danger")
        return redirect(url_for('index.index'))
    
    return render_template("p_perfil.html", id=id, paciente=paciente)
# // >

# Modificar Perfil <
@pac.route('/editar_perfil/<id>', methods=['GET', 'POST'])
def updateProfile(id):

    paciente = Paciente.query.get(id)

    if paciente is None:
        flash('Paciente no encontrado.', 'danger')
        return redirect(url_for('index.index')) 

    if request.method == 'POST':

        paciente.pri_nombre = request.form['pac-pri-nombre']
        paciente.pri_apellido = request.form['pac-pri-apellido']
        paciente.seg_apellido = request.form['pac-seg-apellido']
        paciente.sexo = request.form['pac-sexo']
        paciente.correo = request.form['pac-correo']
        paciente.telefono = request.form['pac-telefono']
        clave = request.form['pac-clave']
        # Hacer la contraseña segura
        paciente.clave = generate_password_hash(clave)   
        # //
        paciente.fecha_nacimiento = request.form['pac-fecha-nacimiento']
        paciente.seg_nombre = request.form['pac-seg-nombre']

        db.session.commit()
        db.session.close()

        flash("Perfil actualizado correctamente", "success")
        return render_template('p_editar_perfil.html', paciente=paciente)
    
    return render_template('p_editar_perfil.html', paciente=paciente)
# // >

# Eliminar Cuenta <
@pac.route('/eliminar_cuenta/<id>', methods=['POST'])
def deleteAccount(id):
    paciente = Paciente.query.get(id)


    if paciente:
        db.session.delete(paciente)
        db.session.commit()
        db.session.close()
        flash("Cuenta eliminada correctamente", "success")
        return redirect(url_for('index.index'))
    else:
        flash("Especialista no encontrado", "danger")
        return redirect(url_for('index.index'))
# // >

# FIXME: Agregar una validacion que si o consigue a ningun especialista muestre un mensaje que diga, usted no tienen un especialista asignado por favor contacte a la fundacion para mas informacion
# Agregar Comida < 
@pac.route('/agregar_comida/<id>', methods=['GET', 'POST'])
def addFood(id):     

    get_pac = db.session.query(Paciente).filter(Paciente.id_paciente == id).first()
    get_esp = db.session.query(
        Especialista.id_espe,
        Especialista.pri_nombre,
        Especialista.pri_apellido
    ).select_from(Comida)\
    .join(Paciente, Comida.id_paciente == Paciente.id_paciente)\
    .join(Especialista, Comida.id_espe == Especialista.id_espe)\
    .filter(
        Paciente.id_paciente == id
    ).distinct().all()
    get_ali = db.session.query(Alimento).all()

    if get_pac is None:
        flash('Paciente no encontrado.', 'danger')
        return redirect(url_for('index.index')) 

    if request.method == 'POST':
        try:
            tipo_comida = request.form['tipo-comida']
            satisfaccion = request.form['satisfaccion']
            comentario = request.form['comentario']
            fecha_ini = request.form['fecha-ini']
            id_espe = request.form['id-espe']

            new_comida = Comida(
                get_pac.id_paciente,
                id_espe,
                fecha_ini,
                tipo_comida,
                satisfaccion,
                comentario
            )
            db.session.add(new_comida)
            db.session.commit()

            print("Comida agregada con exito")
            flash("Comida agregada correctamente", "success")

            _alimento = request.form.getlist('alimentos[]')

            for alimento in _alimento:
                if alimento:
                    new_ac = AC(
                        get_pac.id_paciente,
                        id_espe,
                        fecha_ini,
                        alimento
                    )
                    db.session.add(new_ac)

                    print("Registro de alimento agregado con exito")
                    flash("Registro de alimento agregado con exito")

            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash("Ocurrió un error al agregar la comida.", "danger")
            print(f"Error: {e}")
        finally:
            db.session.close()

        return redirect(url_for('paciente.inicio', id=id))
    
    return render_template('p_add_comida.html', id=id, get_pac=get_pac, get_ali=get_ali, get_esp=get_esp)
# // >

# Detalle de comida <
@pac.route('/detalle_comida/<id>/<date>', methods=["GET"])
def foodDetail(id, date):
    try:
        get_pac = db.session.query(Paciente.id_paciente).filter(Paciente.id_paciente == id).first()
    
        datos = db.session.query(
            Alimento.nombre,
            Alimento.cantidad,
            Alimento.tipo.label('tipo_alimento'),
            Comida.fecha_ini,
            Comida.tipo,
            Comida.satisfaccion,
            Comida.comentario
        ).select_from(Comida).\
        join(AC, Comida.id_paciente == AC.id_paciente).\
        join(Alimento, Alimento.id_alimento == AC.id_alimento).\
        filter(
            Comida.fecha_ini == date, 
            Comida.id_paciente == id,
            AC.fecha_ini == Comida.fecha_ini
        ).distinct().all()
       
        db.session.close()

        date_obj = datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
        date_formatted = date_obj.strftime("%B, %d %Y a las %H:%M")

        return render_template("p_detalle_comida.html", get_pac=get_pac, datos=datos, date=date, date_formatted=date_formatted)
    
    except Exception as e:
        db.session.rollback()
        flash(f"Error en el Detalle de Comida: {e}")
        return render_template(url_for('paciente.inicio', id=id))
# // >

# Modificar Comida <
@pac.route('/editar_comida/<id>/<date>', methods=['GET', 'POST'])
def updateFood(id, date):

    get_pac = db.session.query(Paciente).filter(Paciente.id_paciente == id).first()
    get_ali = db.session.query(Alimento).all()

    if get_pac is None:
        flash('Paciente no encontrado.', 'danger')
        return redirect(url_for('index.index')) 
    
    date_obj = datetime.strptime(date, '%Y-%m-%d %H:%M:%S')
    date_formatted = date_obj.strftime("%B, %d %Y a las %H:%M")

    datos = db.session.query(
        Alimento.nombre,
        Alimento.cantidad,
        Alimento.id_alimento,
        Alimento.tipo.label('tipo_alimento'),
        Comida.fecha_ini,
        Comida.tipo,
        Comida.satisfaccion,
        Comida.comentario
    ).select_from(Comida).\
    join(AC, Comida.id_paciente == AC.id_paciente).\
    join(Alimento, Alimento.id_alimento == AC.id_alimento).\
    filter(
        Comida.fecha_ini == date, 
        Comida.id_paciente == id,
        AC.fecha_ini == Comida.fecha_ini
    ).distinct().all()
             

templates/e_add_comida.html
{% extends 'layout.html' %}

{% block title %}Agregar Comida{% endblock %}

{% block body %}
  
  <a href="{{ url_for('especialista.inicio', id=get_esp.id_espe) }}">Volver</a>
  <h1>Agregar Comida</h1>

  <form action="{{ url_for('especialista.addFood', id=get_esp.id_espe) }}" method="POST" class="form-control">
    
    <div class="form-group">
      <div required>
      <label><input type="radio" name="tipo-comida" value="D">Desayuno</label><br>
      <label><input type="radio" name="tipo-comida" value="A">Almuerzo</label><br>
      <label><input type="radio" name="tipo-comida" value="C">Cena</label><br>
      <label><input type="radio" name="tipo-comida" value="M">Merienda</label><br>
      </div>
    </div>
        
    <div class="form-group">
        <label>Pacientes</label>
        <select name="id-paciente">
            <option value="">Selecciona el nombre</option>
            {% for paciente in get_pac %}
                <option value="{{ paciente.id_paciente }}">{{ paciente.pri_nombre }} {{ paciente.pri_apellido }}</option>
            {% endfor %}
        </select>
    </div>
        
    <!-- Alimentos -->
    <div class="alimentos" id="alimentos">
        <div class="row group">
            <div class="column">
                <div class="form-group">
                    <label>Alimento</label>
                    <select id="alimentos-select" name="alimentos[]">
                        <option value="">Selecciona el nombre</option>
                        {% for alimento in get_ali %}
                            <option value="{{ alimento.id_alimento }}">{{ alimento.nombre }}</option>
                        {% endfor %}
                    </select>
                    <button type="button" id="add-alimento">Agregar otro Alimento</button>
                </div>
            </div>
        </div>
        <ul id="selected-alimentos">
            {% for alimento in selected_alimentos %}
                <li data-id="{{ alimento.id_alimento }}">
                    {{ alimento.nombre }}
                    <input type="hidden" name="alimentos[]" value="{{ alimento.id_alimento }}">
                    <button type="button" class="remove-alimento">Eliminar</button>
                </li>
            {% endfor %}
        </ul>
    </div>
    <!-- // -->
    
    <div class="form-group">
        <h2>Fecha inicio</h2>
        <input type="datetime-local" id="fecha-ini" name="fecha-ini" required>
    </div>

    <div class="form-group">
        <h2>Fecha Fin</h2>
        <input type="datetime-local" id="fecha-fin" name="fecha-fin" required>
    </div>

    <div class="button-container">
      <button class="submit-btn" type="submit">Agregar Comida</button>
    </div>
  </form>

<!-- ZONA DE SCRIPTS -->
<script>

// Para que funcione la entrada multiple de datos en alimento
document.getElementById('add-alimento').addEventListener('click', function() {
    var select = document.getElementById('alimentos-select');
    var selectedValue = select.value;
    var selectedText = select.options[select.selectedIndex].text;

    if (selectedValue) {
        var ul = document.getElementById('selected-alimentos');
        var li = document.createElement('li');
        li.setAttribute('data-id', selectedValue);
        li.innerHTML = selectedText + ' <input type="hidden" name="alimentos[]" value="' + selectedValue + '"> <button type="button" class="remove-alimento">Eliminar</button>';
        ul.appendChild(li);

        select.value = '';
    } else {
        alert("Por favor selecciona un alimento válido.");
    }
});

document.getElementById('selected-alimentos').addEventListener('click', function(e) {
    if (e.target && e.target.classList.contains('remove-alimento')) {
        var li = e.target.parentElement;
        li.parentElement.removeChild(li);
    }
});
// // 

</script>
<!-- // SCRIPTS -->
{% endblock body %}

templates/e_perfil.html
{% extends 'layout.html' %}

{% block title %}Profile Paciente{% endblock %}

{% block body %}

    <a href="{{ url_for('especialista.inicio', id=get_esp.id_espe) }}">Volver</a>

        <p>Nombre {{get_esp.pri_nombre}} {{get_esp.seg_nombre}}</p>
        <p>Apellidos {{get_esp.pri_apellido}} {{get_esp.seg_apellido}}</p>
        <p>Sexo 
            {% if get_esp.sexo == "F" %}
            Femenino
            {% elif get_esp.sexo == "M" %}
                Masculino
            {% elif get_esp.sexo == "O" %}
                Otro
            {% endif %}
        </p>
        <p>Correo {{get_esp.correo}}</p> 
        <p>Telefono {{get_esp.telefono}}</p> 
        <p>Especialidad {{get_esp.especialidad}}</p>
        <p>Clave *******</p> 


        <a href="{{ url_for('especialista.updateProfile', id=get_esp.id_espe) }}">Editar Perfil</a>
        <form action="{{ url_for('especialista.deleteAccount', id=get_esp.id_espe) }}" method="post">
            <input type="submit" value="Eliminar Cuenta">
        </form>
        <a href="{{ url_for('index.logout', id=get_esp.id_espe) }}">Cerrar Sesion</a>
{% endblock %}

templates/e_registro.html
{% extends 'layout.html' %}

{% block title %}Registro Especialista{% endblock %}

{% block body %}

<!-- Static title -->
  <a href="{{ url_for('index.registro') }}">Volver</a>
  <h1>Registro</h1>
  <!-- // -->

    <!-- Action form -->
    <form action="{{ url_for('especialista.registro') }}" method="POST" class="form-control">
        
        <label>Correo Electrónico</label>
        <input type="email" id="esp-correo" name="esp-correo" placeholder="Correo electrónico" required>

        <div class="Paciente Info">
        <label>Primer Nombre</label>
        <input type="text" id="esp-pri-nombre" name="esp-pri-nombre" placeholder="Primer nombre" required>
        
        <label>Segundo Nombre</label>
        <input type="text" id="esp-seg-nombre" name="esp-seg-nombre" placeholder="Segundo nombre">      
        
        <label>Primer Apellido</label>
        <input type="text" id="esp-pri-apellido" name="esp-pri-apellido" placeholder="Primer apellido" required>
        
        <label>Segundo Apellido</label>
        <input type="text" id="esp-seg-apellido" name="esp-seg-apellido" placeholder="Segundo apellido" required>
        
        <div class="form-group">
            <label>Género</label>
            <div requiere>
            <label><input type="radio" name="esp-sexo" value="M">Hombre</label><br>
            <label><input type="radio" name="esp-sexo" value="F">Mujer</label><br>
            <label><input type="radio" name="esp-sexo" value="O">Prefiero no decirlo</label><br>
            </div>
        </div>
        
        <label>Teléfono</label>
        <input type="tel" id="esp-telefono" name="esp-telefono" placeholder="Teléfono" required>
        
        <label>Contraseña</label>
        <input type="password" id="esp-clave" name="esp-clave" placeholder="Contraseña" required>
        
        <label>Especialidad</label>
        <input type="text" id="esp-especialidad" name="esp-especialidad" placeholder="Especialidad" required>
        
        <!-- Boton -->
        <div class="button-container">
            <button class="submit-btn" type="submit">Aceptar</button>
        </div>
        <!-- // -->

    </form>

    <a href="{{ url_for('static', filename='terms_conditions.html') }}">Al continuar acepta nuestros términos y condiciones.</a>

    <script>
        document.querySelector('form').addEventListener('submit', function(event) {
            var sexo = document.querySelector('input[name="esp-sexo"]:checked');
            if (!sexo) {
                alert('Por favor, selecciona una opción de género.');
                event.preventDefault();
            }
        });
    </script>
{% endblock body %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}Inicio{% endblock %}

{% block body %}
  <!-- Text Area -->
    <h1>Bienvenido</h1>
    <h4>Descubre un camino hacia una alimentación saludable y equilibrada. Aprende a nutrir tu cuerpo de manera consciente, alcanza un bienestar integral</h4>

    <!-- Buttons -->
    <a href="{{ url_for('index.login') }}">Iniciar Sesion</a>
    <a href="{{ url_for('index.registro') }}">Registrarse</a>

{% endblock %}

templates/login.html
{% extends 'layout.html' %}

{% block title %}Inicio de Sesion{% endblock %}

{% block body %}

    <!-- Static title -->
    <a href="{{ url_for('index.index') }}">Volver</a>
    <h1>Es un gusto tenerte de nuevo</h1>
    <!-- // -->

    <!-- Form -->
    <div>
        <form action="{{ url_for('index.login') }}" method="POST">
            <h2>Por favor ingresa tus datos</h2>

            <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" placeholder="Enter email" name="ind-correo">
            </div>

            <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" placeholder="Password" name="ind-clave">
            </div>

            <a href="/#"><small id="emailHelp" class="form-text text-muted">¿Olvidó su Contraseña?</small></a>
            <small>¿No tienes una cuenta? <a href="{{ url_for('index.registro') }}">Registrese</a></small>
            
            <button type="submit">Iniciar Sesion</button>
        </form>
    </div>
    <!-- // -->

{% endblock %}

templates/p_add_comida.html
{% extends 'layout.html' %}

{% block title %}Agregar Comida{% endblock %}

{% block body %}
  
  <a href="{{ url_for('paciente.inicio', id=get_pac.id_paciente) }}">Volver</a>
  <h1>Agregar Comida</h1>

  <form action="{{ url_for('paciente.addFood', id=get_pac.id_paciente) }}" method="POST" class="form-control">
    
    <div class="form-group">
        <label>Especialistas</label>
        <select name="id-espe">
            <option value="">Selecciona el nombre</option>
            {% for espe in get_esp %}
                <option value="{{ espe.id_espe }}">{{ espe.pri_nombre }} {{ espe.pri_apellido }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group">
      <div required>
      <label><input type="radio" name="tipo-comida" value="D">Desayuno</label><br>
      <label><input type="radio" name="tipo-comida" value="A">Almuerzo</label><br>
      <label><input type="radio" name="tipo-comida" value="C">Cena</label><br>
      <label><input type="radio" name="tipo-comida" value="M">Merienda</label><br>
      </div>
    </div>

    <!-- Alimentos -->
    <div class="alimentos" id="alimentos">
        <div class="row group">
            <div class="column">
                <div class="form-group">
                    <label>Alimento</label>
                    <select id="alimentos-select" name="alimentos[]">
                        <option value="">Selecciona el nombre</option>
                        {% for alimento in get_ali %}
                            <option value="{{ alimento.id_alimento }}">{{ alimento.nombre }}</option>
                        {% endfor %}
                    </select>
                    <button type="button" id="add-alimento">Agregar otro Alimento</button>
                </div>
            </div>
        </div>
        <ul id="selected-alimentos">
            {% for alimento in selected_alimentos %}
                <li data-id="{{ alimento.id_alimento }}">
                    {{ alimento.nombre }}
                    <input type="hidden" name="alimentos[]" value="{{ alimento.id_alimento }}">
                    <button type="button" class="remove-alimento">Eliminar</button>
                </li>
            {% endfor %}
        </ul>
    </div>
    <!-- // -->

    <h2>¿Como te sientes?</h2>
    <div class="form-group">
        <div>
            <label><input type="radio" name="satisfaccion" value="Super"> Super</label><br>
            <label><input type="radio" name="satisfaccion" value="Bien"> Bien</label><br>
            <label><input type="radio" name="satisfaccion" value="Normal"> Normal</label><br>
            <label><input type="radio" name="satisfaccion" value="No muy bien"> No muy bien</label><br>
            <label><input type="radio" name="satisfaccion" value="Nal"> Mal</label><br>
            <label><input type="radio" name="satisfaccion" value="Cansado"> Cansado</label><br>
        </div>
    </div>

    <h2>Comentario</h2>
    <div>
        <textarea id="comentario" name="comentario"></textarea>
    </div>
    
    <div class="form-group">
        <h2>Fecha</h2>
        <input type="datetime-local" id="fecha-ini" name="fecha-ini" required>
    </div>

    <div class="button-container">
      <button class="submit-btn" type="submit">Agregar Comida</button>
    </div>
  </form>

<!-- ZONA DE SCRIPTS -->
<script>

// Para que funcione la entrada multiple de datos en alimento
document.getElementById('add-alimento').addEventListener('click', function() {
    var select = document.getElementById('alimentos-select');
    var selectedValue = select.value;
    var selectedText = select.options[select.selectedIndex].text;

    if (selectedValue) {
        var ul = document.getElementById('selected-alimentos');
        var li = document.createElement('li');
        li.setAttribute('data-id', selectedValue);
        li.innerHTML = selectedText + ' <input type="hidden" name="alimentos[]" value="' + selectedValue + '"> <button type="button" class="remove-alimento">Eliminar</button>';
        ul.appendChild(li);

        select.value = '';
    } else {
        alert("Por favor selecciona un alimento válido.");
    }
});

document.getElementById('selected-alimentos').addEventListener('click', function(e) {
    if (e.target && e.target.classList.contains('remove-alimento')) {
        var li = e.target.parentElement;
        li.parentElement.removeChild(li);
    }
});
// // 

</script>
<!-- // SCRIPTS -->
{% endblock body %}

templates/p_perfil.html
{% extends 'layout.html' %}

{% block title %}Perfil Paciente{% endblock %}

{% block body %}

    <a href="{{ url_for('paciente.inicio', id=paciente.id_paciente) }}">Volver</a>

        <p>Nombre {{paciente.pri_nombre}} {{paciente.seg_nombre}}</p>
        <p>Apellidos {{paciente.pri_apellido}} {{paciente.seg_apellido}}</p>
        <p>Sexo 
            {% if paciente.sexo == "F" %}
            Femenino
            {% elif paciente.sexo == "M" %}
                Masculino
            {% elif paciente.sexo == "O" %}
                Otro
            {% endif %}
        </p>
        <p>Correo {{paciente.correo}}</p> 
        <p>Telefono {{paciente.telefono}}</p> 
        <p id="edad">Edad </p>
        <p>Clave *******</p> 


        <a href="{{ url_for('paciente.updateProfile', id=paciente.id_paciente) }}">Editar Perfil</a>
        <form action="{{ url_for('paciente.deleteAccount', id=paciente.id_paciente) }}" method="post">
            <input type="submit" value="Eliminar Cuenta">
        </form>
        <a href="{{ url_for('index.logout', id=paciente.id_paciente) }}">Cerrar Sesion</a>

        <script>
            const fechaNacimiento = "{{ paciente.fecha_nacimiento }}";
    
            function calcularEdad(fecha) {
                const hoy = new Date();
                const nacimiento = new Date(fecha);
                let edad = hoy.getFullYear() - nacimiento.getFullYear();
                const mes = hoy.getMonth() - nacimiento.getMonth();
                if (mes < 0 || (mes === 0 && hoy.getDate() < nacimiento.getDate())) {
                    edad--;
                }
                return edad;
            }
    
            const edad = calcularEdad(fechaNacimiento);
            document.getElementById('edad').textContent = `Edad: ${edad}`;
        </script>
{% endblock %}

templates/password_recovery.html
{% extends 'layout.html' %}

{% block title %}Recuperacion de Contraseña{% endblock %}

{% block body %}

<h1>Recuperación de contraseña</h1>
<form method="POST">
    <label for="email">Correo electrónico:</label>
    <input type="email" id="email" name="email" required>
    <input type="submit" value="Recuperar contraseña">
</form>
{% endblock %}

templates/recover_password.html
{% extends 'layout.html' %}

{% block title %}Recuperacion de Contraseña{% endblock %}

{% block body %}

    <h1>Recuperación de contraseña</h1>
    <p>Para recuperar tu contraseña, por favor haz clic en el siguiente enlace:</p>
    <a href="{{ confirm_url }}">Recuperar contraseña</a>

{% endblock %}